### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by robbertzhang** [shmir/PyIxExplorer#3]
tclproto.py  line 74: io_output, result = data.
please correct it.

**Comment by shmir** [comment]
Hi,
Could you be more specific please?
Thanks,
Yoram

**Comment by robbertzhang** [comment]
File: tclproto.py
Line:74
Code: io_output, result = data
Comments: Python syntax error，could be io_output，result = data[0], data[1], or other code

**Comment by shmir** [comment]
Can't find it...
IDE does not show and error and code works just fine both with python 2.7 and 3.6.
Yoram

**Comment by robbertzhang** [comment]
Is the branch right？mine is master.
file path:  ixexplorer\api\tclproto.py
It's in function socket_call. It's no matter about python version. 
finally, if you still can't find it, I have nothing to say

**Comment by shmir** [comment]
I'm on master and don't see it :(
Maybe it's IDE issue?
Interesting...
